USE pds;

SELECT * 
FROM employees
ORDER BY FIRST_NAME;

SELECT FIRST_NAME , LAST_NAME, SALARY, SALARY * 0.15 AS TAXES
FROM employees
ORDER BY FIRST_NAME;

SELECT SUM(SALARY) AS TOTAL_SALARY
FROM employees;

SELECT MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY
FROM employees;

SELECT AVG(SALARY) AS AVG_SALARY
FROM employees;